baseURL = "https://<your-github-username>.github.io/"
languageCode = "en-us"
title = "Gdańsk CA Group"
theme = "PaperMod"

[params]
  defaultTheme = "light"
  ShowReadingTime = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  math = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[outputs]
  home = [ "HTML", "RSS", "JSON" ]

  [menu]

  [[menu.main]]
  name = "News"
  url = "/news/"
  weight = 1

  [[menu.main]]
  name = "Team"
  url = "/team/"
  weight = 2

  [[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 3

  [[menu.main]]
  name = "Contact Us"
  url = "/contact/"
  weight = 10

  [[menu.main]]
  name = "Research Interests"
  url = "/research-interests/"
  weight = 5

  [[menu.main]]
  name = "Partners"
  url = "/partners/"
  weight = 6
